In [16]:
import random
from math import cos, sin


import matplotlib.pyplot as plt
import numpy as np
import utils

In [33]:
!pip install checker

  Using cached checker-1.9.tar.gz (24 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'


  error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [6 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\tomas\AppData\Local\Temp\pip-install-qe8cytke\checker_eed5c460fcdf46b3acb593d3b556b510\setup.py", line 5, in <module>
      from ConfigParser import RawConfigParser
  ModuleNotFoundError: No module named 'ConfigParser'
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


## Po co nam to numpy?
Przydaje nam się z kilku powodów:
* Napisanie jednej linijki w numpy jest szybsze i wygodniejsze niż napisanie pętli, jest też mniejsza szansa, że zrobimy gdzieś po drodze błąd. Oczywiście najpierw trzeba się przyzwyczaić do intefejsu.
* Numpy jest znacznie bardziej wydajny niż napisane przez nas funkcje w "czystym" Pythonie.
* PyTorch, biblioteka do głębokiego uczenia, z której później będziemy korzystać, ma bardzo podobny interfejs.

### Kilka przykładów

In [18]:
%%timeit

X = [random.random() for _ in range(10000)]
y = [sin(x) + cos(x) for x in X]

3.05 ms ± 307 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [20]:
%%timeit

X = np.random.random(10000)
y = np.sin(X) + np.cos(X)

224 μs ± 34.8 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [22]:
def almost_variance(x: np.ndarray) -> np.ndarray:
    """Oblicza 1/n * SUM (x_i - mean(x))^4"""
    m = sum(x) / len(x)
    result = 0
    for i in range(len(x)):
        result += (x[i] - m) ** 4
    result /= len(x)
    return result


def numpy_almost_var(x: np.ndarray) -> np.ndarray:
    m = np.mean(x)
    powers = (x - m) ** 4
    return np.mean(powers)


X = np.random.random(10000)

In [24]:
%%timeit
almost_variance(X)

5.03 ms ± 618 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [26]:
%%timeit
numpy_almost_var(X)

358 μs ± 36.1 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


## Zadanie 1. (3 pkt.)
Wykonać poniższe ćwiczenia przy pomocy Numpy:

1. Wykorzystując `broadcasting` (patrz na rysunek poniżej) stwórz funkcję, która dla zadnego $K$ zwraca tabliczkę mnożenia, tzn. tablicę $A$ taką, że: $$A_{ij} = i \cdot j\;\;\;\;\; \forall i,j \in \{1,\dots,K\}$$
    <img src="http://www.astroml.org/_images/fig_broadcast_visual_1.png">

    Przydatne funkcje: `np.arange`, `np.reshape`. 

In [ ]:
def multiplication_table(k: int) -> np.ndarray:
    ...


print("Wynik funkcji multiplication:\n", multiplication_table(10))
checker.check_multiplication_table(multiplication_table)

In [35]:
import numpy as np

def multiplication_table(k: int) -> np.ndarray:

    row = np.arange(k).reshape((k, 1))
    table = row + np.arange(k)
    
    return table

# Przykład działania funkcji
print("Wynik funkcji multiplication_table:\n", multiplication_table(10))
#checker.check_multiplication_table(multiplication_table)

Wynik funkcji multiplication_table:
 [[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]]


2. Mając daną tablice jednowymiarową oraz liczbę `x` znajdź najbliższą wartość `x` w `A`, tzn. 
    $$ \mathrm{closest}(x, A) = \arg\min_{a\in A}|x - a|  $$

    Przydatne funkcje: `np.argmin`, `np.abs`. 

In [39]:
def closest(x: float, A: np.ndarray) -> np.ndarray:
    ...


print("Wynik funkcji closest:", closest(9, np.array([5, 8, 10])))
checker.check_closest(closest)

Wynik funkcji closest: None


NameError: name 'checker' is not defined

In [51]:
import numpy as np

def closest(x: float, A: np.ndarray) -> np.ndarray:
    differences = np.abs(A - x)
    closest_index = np.argmin(differences)
    return A[closest_index]

print("Wynik funkcji closest:", closest(9, np.array([5, 8, 10])))

Wynik funkcji closest: 8


3. Zaimplementuj proste liczenie wartosci wielomianu o zadanych współczynnikach (analogię `np.poly1d`), czyli funkcję

    $$
    \mathrm{poly}(x, a) = a_0 + a_1 x + a_2 x^2 + \dots + a_k x^k = \sum_{i=1}^k a_i x^i
    $$

    Potencjalnie przydatne funkcje: `np.cumprod`, `np.concatenate`, `np.sum`.

In [ ]:
def poly(x: int, a: np.ndarray) -> np.ndarray:
    ...


print("Wynik funkcji poly:", poly(3, np.array([1, 2, 4])))
checker.check_poly(poly)

In [56]:
def poly(x: int, a: np.ndarray) -> np.ndarray:
    # Tworzymy tablicę potęg x: [x^0, x^1, x^2, ..., x^k]
    powers = np.arange(len(a))
    
    # Mnożymy współczynniki a przez odpowiednie potęgi x
    result = a * (x ** powers)
    
    # Sumujemy wyniki, aby uzyskać wartość wielomianu
    return np.sum(result)

print("Wynik funkcji poly:", poly(3, np.array([1, 2, 4])))


Wynik funkcji poly: 43


## Zadanie 2. (2 pkt.)
Dla macierzy $X$ o wymiarze `[N, D]` zaimplementować operację whiteningu: 

$\mathrm{whiten}(X) = (X-\mathrm{mean} X)(\mathrm{cov} X)^{-1/2}$

$\mathrm{mean} X$ rozumiemy jako wektor wierszowy, którego każdy element jest zdefiniowany jako: $$(\mathrm{mean}X)_i = \frac{1}{N} \sum_{j=1}^N X_{ij}$$

**Uwaga 1: np.cov przyjmuje, że każdy wiersz macierzy to osobna cecha, a każda kolumna to osobna obserwacja - czyli odwrotnie niż u nas. Dlatego przed podaniem naszej macierzy do np.cov trzeba ją transponować.**

**Uwaga 2: pierwiastek z macierzy to nie to samo co pierwiastkowanie element-wise, takie jak w np.sqrt. Najlepiej poszukać odpowiedniej funkcji w bibliotece scipy i ją zaimportować.**

In [ ]:
# from scipy.linalg import ???


def whiten(X: np.ndarray) -> np.ndarray:
    ...

In [ ]:
X_diag_normal = np.random.multivariate_normal([-5, 2.0], [[10, 0], [0, 0.5]], size=200)
X_multivariate_normal = np.random.multivariate_normal([-5, -2], [[1, 0.99], [0.99, 1]], size=500)
X_uniform = np.random.normal(6, 5, size=(50, 2))
X_gmm = np.concatenate((X_multivariate_normal, X_diag_normal), axis=0)

utils.scatter_with_whiten(X_diag_normal, whiten, name="Independent normal distribution")
utils.scatter_with_whiten(X_multivariate_normal, whiten, name="Multivariate normal distribution")
utils.scatter_with_whiten(X_uniform, whiten, name="Uniform distribution")
utils.scatter_with_whiten(X_gmm, whiten, name="Gaussian mixture distribution")

In [58]:
from scipy.linalg import sqrtm

def whiten(X: np.ndarray) -> np.ndarray:
    # 1. Obliczamy średnią dla każdego wymiaru
    meanX = np.mean(X, axis=0)
    
    # 2. Odejmujemy średnią od danych
    X_centered = X - meanX
    
    # 3. Transponujemy macierz i obliczamy macierz kowariancji
    covX = np.cov(X_centered, rowvar=False)  # `rowvar=False`, ponieważ kolumny są cechami
    
    # 4. Obliczamy odwrotność pierwiastka macierzy kowariancji
    covX_inv_sqrt = np.linalg.inv(sqrtm(covX))
    
    # 5. Zastosowanie whitening: (X - meanX) * (covX)^(-1/2)
    X_whitened = X_centered.dot(covX_inv_sqrt)
    
    return X_whitened

# Przykład użycia funkcji
X = np.random.multivariate_normal([5, -2], [[10, 3], [3, 2]], size=500)
X_whitened = whiten(X)
print(X_whitened)

[[ 5.20379654e-01  2.01234835e-01]
 [ 7.07726010e-01  4.13403896e-01]
 [-1.04947874e+00  2.61348002e-01]
 [-9.42125815e-01  2.84046415e-01]
 [-1.34930805e-01  5.95629998e-01]
 [-9.62429085e-02 -8.13411289e-01]
 [ 8.11104408e-02  1.63741695e-01]
 [ 1.08024290e+00  7.82950827e-01]
 [ 5.59824873e-01  8.44025231e-01]
 [-2.24178660e-01  8.72430922e-01]
 [-7.27600630e-01 -3.19948179e-02]
 [ 1.91523902e+00 -2.95741561e-01]
 [ 5.33787211e-01 -4.24028724e-02]
 [-1.95261559e+00 -1.72031445e+00]
 [-4.53702105e-01  4.42124359e-01]
 [-1.30077882e+00  1.36025876e+00]
 [-6.32240971e-01 -4.21838386e-01]
 [ 1.76289874e+00 -6.21012201e-01]
 [ 5.10198179e-01 -1.53844871e+00]
 [-6.97417436e-01 -1.40590704e+00]
 [ 5.49813408e-01  1.15108300e+00]
 [-1.17697847e+00  6.67816786e-01]
 [ 9.35187257e-02  2.22348632e+00]
 [-3.08614963e-01 -1.58163399e+00]
 [-5.72122414e-01  1.40208559e+00]
 [-8.18441022e-01  7.52801024e-01]
 [ 8.39589000e-01  1.00296142e+00]
 [-1.27832880e+00  2.06956266e+00]
 [-7.36011762e-01  8

## Standaryzacja a whitening
W pierwszym notebooku implementowaliśmy następującą funkcję, która wykonuje zadanie podobne do whiteningu:

$$ f(x_{ij}) = \frac{x_{ij} - \mu_j}{\sigma_j} $$

Tę funkcję nazwijmy **standaryzacją**. Czym zatem różni się standaryzacja od whiteningu? Czy nie wystarczy znormalizować kolumn i zamiast tego musimy wykonywać znacznie bardziej kosztowną operację liczenia i odwracania macierzy kowariancji?

In [ ]:
utils.scatter_with_whiten(
    X_diag_normal, whiten, name="Independent normal distribution", standarize=True
)
utils.scatter_with_whiten(
    X_multivariate_normal, whiten, name="Multivariate normal distribution", standarize=True
)
utils.scatter_with_whiten(X_uniform, whiten, name="Uniform distribution", standarize=True)
utils.scatter_with_whiten(X_gmm, whiten, name="Gaussian mixture distribution", standarize=True)

In [64]:
import numpy as np
from scipy.linalg import sqrtm

# Standaryzacja: f(xij) = (xij - uj) / rj
def standardize(X: np.ndarray) -> np.ndarray:
    # Oblicz średnią i odchylenie standardowe dla każdej kolumny
    mean = np.mean(X, axis=0)
    std_dev = np.std(X, axis=0)
    
    # Standaryzuj: (X - mean) / std_dev
    return (X - mean) / std_dev

# Whitening z regularizacją
def whiten(X: np.ndarray, epsilon: float = 1e-5) -> np.ndarray:
    # 1. Odjęcie średniej od każdej cechy
    X_centered = X - np.mean(X, axis=0)
    
    # 2. Obliczenie macierzy kowariancji
    cov = np.cov(X_centered, rowvar=False)
    
    # 3. Dodanie małej wartości do diagonalnych elementów macierzy kowariancji (regularizacja)
    cov += epsilon * np.eye(cov.shape[0])
    
    # 4. Obliczenie odwrotności pierwiastka macierzy kowariancji
    cov_inv_sqrt = np.linalg.inv(sqrtm(cov))
    
    # 5. Przekształcenie macierzy X na postać whitened
    X_whitened = X_centered @ cov_inv_sqrt
    return X_whitened

# Przykładowe dane
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])

# Zastosowanie standaryzacji
X_standardized = standardize(X)
print("Standaryzacja:\n", X_standardized)

# Zastosowanie whiteningu z regularizacją
X_whitened = whiten(X)
print("Whitening:\n", X_whitened)

Standaryzacja:
 [[-1.34164079 -1.34164079]
 [-0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079]]
Whitening:
 [[-0.82158353 -0.82158353]
 [-0.27386118 -0.27386118]
 [ 0.27386118  0.27386118]
 [ 0.82158353  0.82158353]]


## Zadanie 3. (2 pkt.)
Należy:
1. Wysamplować $10000$ przykładów z rozkładu normalnego $\mathcal{N}(\mu, \sigma)$. **Należy wybrać niestandardowe parametry**, tzn. $\mu \neq 0$ oraz $\sigma \neq 1$.
2. Następnie należy policzyć, jaki procent wylosowanych przykładów, znajduje się od środka w odległości większej niż: 
    * $1\sigma$ (tzn. $|x - \mu| > 1\sigma$)
    * $2\sigma$ (tzn. $|x - \mu| > 2\sigma$)
    * $3\sigma$ (tzn. $|x - \mu| > 3\sigma$)
    
3. Wypisać wszystkie przykłady, które wpadają do ostatniej kategorii (tzn. są oddalone o co najmniej $3\sigma$ od średniej).

In [ ]:
# Podpunkt 1: Wysamplować 10000 przykładów z rozkładu normalnego
loc = ???  # średnia wybranego rozkładu normalnego
scale = ???  # odchylenie standardowe wybranego rozkładu normalnego
X = np.random.normal(???)

# Podpunkt 2: Wyliczyć i wypisać procent 

# Podpunkt 3: Wypisać elementy, które są oddalone od średniej o 3 sigma.

# Trochę wizualizacji
utils.visualize_normal_dist(X, loc, scale)

In [66]:
# Podpunkt 1: Wysamplować 10000 przykładów z rozkładu normalnego o niestandardowych parametrach
loc = 5  # średnia wybranego rozkładu normalnego
scale = 2  # odchylenie standardowe wybranego rozkładu normalnego
X = np.random.normal(loc, scale, 10000)

# Podpunkt 2: Obliczyć, jaki procent przykładów znajduje się w odległości większej niż 1σ, 2σ, 3σ od średniej
mean_X = np.mean(X)
std_X = np.std(X)

# Obliczenie procentów
percent_1_sigma = np.mean(np.abs(X - mean_X) > 1 * std_X) * 100
percent_2_sigma = np.mean(np.abs(X - mean_X) > 2 * std_X) * 100
percent_3_sigma = np.mean(np.abs(X - mean_X) > 3 * std_X) * 100

# Wyświetlanie wyników
print(f"Procent przykładów odległych o więcej niż 1σ od średniej: {percent_1_sigma:.2f}%")
print(f"Procent przykładów odległych o więcej niż 2σ od średniej: {percent_2_sigma:.2f}%")
print(f"Procent przykładów odległych o więcej niż 3σ od średniej: {percent_3_sigma:.2f}%")

# Podpunkt 3: Wypisać elementy, które są oddalone od średniej o co najmniej 3σ
outliers_3_sigma = X[np.abs(X - mean_X) > 3 * std_X]
print(f"Liczba elementów oddalonych o co najmniej 3σ od średniej: {len(outliers_3_sigma)}")
print("Te elementy to:", outliers_3_sigma)

Procent przykładów odległych o więcej niż 1σ od średniej: 31.81%
Procent przykładów odległych o więcej niż 2σ od średniej: 4.51%
Procent przykładów odległych o więcej niż 3σ od średniej: 0.28%
Liczba elementów oddalonych o co najmniej 3σ od średniej: 28
Te elementy to: [11.55654838 11.52989551 -2.09335609 11.3530644  11.05922776 11.32839171
 -1.18926193 -1.50973288 -1.25446517 -1.69970923 -1.23229178 -1.1483554
 -1.54936668 11.18329301 11.41850132 -2.11871021 -1.12383012 -1.29819458
 12.13032863 -1.74056966 11.09349897 -1.70407405 -1.51824266 13.89543558
 -1.05426556 -1.21095437 11.27830113 -1.20745388]
